name: Build, Deploy, and Upload Artifacts to JFrog

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: 

      # Configure Maven settings for JFrog Artifactory
      - name: Configure Maven settings for Artifactory
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>hello-world-war</id>
                      <username>${{ secrets.ARTIFACTORY_USERNAME }}</username>
                      <password>${{ secrets.ARTIFACTORY_API_KEY }}</password>
                    </server>
                  </servers>
                  <profiles>
                    <profile>
                      <id>hello-world-war</id>
                      <repositories>
                        <repository>
                          <id>hello-world-war-libs-release</id>
                          <url>http://43.205.239.147:8082/artifactory/hello-world-war-libs-release//url>
                        </repository>
                      </repositories>
                    </profile>
                  </profiles>
                </settings>" > ~/.m2/settings.xml

      # Build the project with Maven (package phase to create the artifact)
      - name: Build with Maven
        run: mvn clean package

      # Deploy the artifact to JFrog Artifactory
      - name: Deploy to JFrog Artifactory
        run: mvn deploy -DaltDeploymentRepository=artifactory::default::https://your-artifactory-instance/artifactory/your-repo

